### ISSUE TITLE
Figure references sometimes not working

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#410]
In a bunch of different places in concept pages, references to figures are simply reading "Figure" without a number e.g. https://staging.isaacphysics.org/concepts/cp_fields

**Comment by jsharkey13** [comment]
This seems to be an issue with underscores inside the references.

See Section 3 on [this page](http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/concepts/physics/electrical_components.json) (Diodes): where there are two references with underscores in. One has plain underscores, the second one has backslash-escaped underscores. Neither render correctly on staging:

![image](https://cloud.githubusercontent.com/assets/8060558/9522257/c8671228-4ccb-11e5-8db9-e05f28437b46.png)


![image](https://cloud.githubusercontent.com/assets/8060558/9522273/de4c58dc-4ccb-11e5-8f4e-d1fa5dc40e7d.png)

**Comment by jsharkey13** [comment]
Now it appears not to be consistent; there are some references (notably http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/concepts/physics/electric_field.json ) that work just fine with underscores in.

I've no idea how I'd go about working out what's going wrong where.

This could do with being a priority fix though . . .

**Comment by alistairstead3408** [comment]
This is a naming issue. In https://staging.isaacphysics.org/concepts/cp_fields
The first figure ref in the content is \ref{electric_field_potential_point_scalar_illustration}

On the front end, this is listed under the ID: cp_fields|electric_field_potential_point_scalar_illustration

This doesn't match any object in the scope.figures array in FigureRef.js, because that contains cp_fields|acc_cp_fields_scalar_fields|electric_field_potential_point_scalar_illustration

It looks like the ID acc_cp_fields_scalar_fields is being missed.

**Comment by mjc209** [comment]
This is still a problem

**Comment by daviesian** [comment]
Fixed in baa682730300c9e38d77e2e24a0730ace6c7b976.

Please open a new issue for any further figure referencing bugs.
