### ISSUE TITLE
Difficult for users to choose correct school name

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#548]
I was updating an account to have teacher status. Knowing that the teacher came from Notre Dame High School, norwich, I began entering notre dame high school in the school box. There were several notre dame high schools listed without post codes.

![image](https://cloud.githubusercontent.com/assets/10402385/10059798/f56516d8-6244-11e5-9299-dccbeb3b4120.png)

So I google notre dame high school, copy the post code and paste that into the school box, and this appears - i.e. now ndhs is not in the list at all.
![image](https://cloud.githubusercontent.com/assets/10402385/10059839/32b3cb92-6245-11e5-945f-e16d01fd82aa.png)

This may be related to the issue of URNs that Heather raised.

It is definitely an impediment to us gathering good data on which school a user is from, if they themselves can't be sure they've picked the right name.

**Comment by sacummins** [comment]
The data is as per the DfE download and is correct according to our data source.

If we want to prevent users selecting schools that the DfE deem to be active but do not have registered post codes then that is a separate issue and should be discussed at length - as this will prevent users entering schools with valid URNs in certain cases.

**Comment by allydavies** [comment]
OK, I have no idea how many schools are affected in this way - it is essentially schools that share a name with another school (or indeed are duplicated as per Heather's issue), AND that ALSO have no listed postcode on our DFE list. It's definitely more complex than the double entry issue as we can count the students at double registered schools as being at the same school. Here a student or teacher just has no way of knowing which school to choose, and has no way to indicate which is their school.
Is there any way we can
(a) establish how many schools might fit these criteria (I don't have any data source that gives me matching URNs, names and postcodes) and perhaps then
(b) edit the data source so we DO provide the post code OR town name etc so users could then choose their school from the list?

wrt removing valid URNs from the list...
I don't think we'd lose much by removing e.g. "Hills Road Adult Community Education" as a school with a valid URN. There is very low probability of anyone being taught A level physics at such an institution.
I am NOT suggesting that we should only offer ONE Notre Dame School (as these are genuinely different schools in different towns with the same name). We don't want everyone who goes to *any* Notre Dame School to have to pick the one Notre Dame that's listed, but instead to have some way to see which is THEIR Notre Dame school.

**Comment by allydavies** [comment]
So now, I do have some idea - of approx 1000 schools with linked accounts about 250 are schools with issues relating to their name / postcode. In addition, there are schools which do not appear on the list at all - one such is 
![image](https://cloud.githubusercontent.com/assets/10402385/12726704/ef05969a-c910-11e5-8dd0-bcf5a2d2828c.png)

If I type "saint bede's":
![image](https://cloud.githubusercontent.com/assets/10402385/12726740/203a6204-c911-11e5-881d-bd8814044d56.png)

Or "St bede's":
![image](https://cloud.githubusercontent.com/assets/10402385/12726768/47abb950-c911-11e5-95f0-b7d3b6f391cf.png)

The correct postcode is not one of the options.

**Comment by allydavies** [comment]
Another school to add to our dropdown (recently changed its name) is:
The Oaks Academy, Crewe, CW2 7NQ - URN 142472
Formerly King’s Grove High School

ALSO
Do we make any systematic attempt to follow changes in DfE database - e.g termly annual update?

**Comment by jsharkey13** [comment]
The school CSV list has had an extensive and time consuming overhall:

* I have removed all schools without postcodes and then added back those which had Isaac users and gave them a relevant postcode (only 3, all split sixth forms: I picked one of the subsidiary school postcodes after verifying they were all within a mile of one another in each case).

* I have removed primary schools and nurseries from the list. The users (>50) at these schools will lose their association and hopefully provide us an accurate one!

* Schools with the same name as another school (ignoring postcode) have had their town/city/locale appended to them for extra clarity. This was only feasible for schools with exactly the same name, but if it's still an issue we can more easily modify the list now.

* Schools which featured highly in the school other list were identified and it was usually because the school went by an acronym or short name we didn't have. I added these in brackets to the relevant schools.

* I have manually altered the information of several schools to make it clearer, add a short name or town name. This will make updating to the next DfE data dump slightly harder; but actually VLOOKUP in Excel on school URN is a pretty effective measure for pairing up. We haven't updated in two years, so I don't mind a day-long process every year!
