### ISSUE TITLE
Pod "dots" bar has one too many dots

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#594]
![image](https://cloud.githubusercontent.com/assets/8060558/10733079/0185dd5c-7bf5-11e5-9ce6-16f15d8c6d82.png)

Navigating through all the pods until the arrow does nothing doesn't get the last green dot underneath to be highlighted. Either there are too many dots, or something else has gone wrong. I thought this was a content issue about numbering and ID's, but that didn't fix it.

**Comment by jsharkey13** [comment]
It doesn't seem to be an issue on mobile though!

**Comment by alistairstead3408** [comment]
This is an issue with owl carousel - the library we are using. The reason for it working differently on mobile is that the dots are calculated incorrectly. In the case above there are 10 pods - not a multiple of the number of visible pods (3). The last dot takes shows you pods 8, 9, 10 - it doesn't highlight correctly when you land on it because it calculates the dot position based on which pod is in the first visible pod, and which triple it should appear in. 

This will be addressed somehow in the home page update.

**Comment by alistairstead3408** [comment]
@daviesian has updated owl carousel, who have fixed the issue in their code. The fix will be released with the updated home page.
