### ISSUE TITLE
csv download - columns not in the right order

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#629]
I have seen a csv from a teacher who had set questions 1-12 of J2 (there are 18 parts to J2).
It appears that the columns don't match the questions.
The class said they had done parts 1-12 . The s/s shows that all but one of the students HAD done 12 parts; four of the students had done ALL parts.

In the s/s, we'd expect to see all students with data for the first 12 columns, but we don't, we see columns, 4, 8, 11, 14, 16, 18 are the ones that only four people have done.

If teachers are using this to work out what's the question to go through in class then they will be mislead.

This question set includes questions in a table. Is that part of the problem?
Is the isssue general, or specific to this page of the book, or related to certain types of page?
Have asked for screenshots to help us troubleshoot.

**Comment by jsharkey13** [comment]
This was fixed in https://github.com/ucam-cl-dtg/isaac-api/commit/54c19fe456b2d8938cb6d9628130f05dfe95a32f, and the numbering has since been changed so that it intentionally does not match the front end to avoid any possible confusion when there are multiple questions per accordion section and the letter assignment went  wrong . . .
