### ISSUE TITLE
Events: enter end time

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#655]
At the moment you can only enter a date and start time onto an isaac event page.  It would be good to be able to give the end time (and in the case of residentials, end date)

**Comment by allydavies** [comment]
In fact it would also be good to be able to give just a date. For example, when we are contributing a session at an all day event we might have our session in two time slots, so giving one is misleading and the booking would all be done through the third party (e.g. Ogden or Stimulating Physics Network).

**Comment by mjc209** [comment]
It would be good for virtual events to stay on the events page until an end time too

**Comment by jsharkey13** [comment]
Right now, the code won't be released and you can't edit `"end_date"` from the editor. If you specify and end date, then the event won't expire until then. If you set the `"end_date"` to be 24 hours (or more) after the `"date"`, the event will be assumed to be an all day event.

For the sake of people's calendars (they can probably extract the time from Isaac even though it's hidden) I recommend that all day events should have times set to midnight on the morning of the event, and so all day events thus have an end_date of midnight the next morning.

---

If you really need to specify an `"end_date"` before anything is added to the editor, use the date field in the metadata to enter the end date, then copy the JSON line for the date, changing the key to `"end_date"`. Then close the JSON and go back to the metadata to change the start date as usual. Be careful; because events may not expire or show up if these dates are messed up (or back to front).
Also, I wrote this code alone - so it might not work. Please keep an eye on it when you first use it.
