### ISSUE TITLE
Regular placement of correct answers for multiple choice

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#665]
When a page has several multiple choice questions with the same number of answers, e.g.https://isaacphysics.org/gameboards#physicsskills_book_ch_d5 , the correct answer will be in the same position for each question. Apparently some students have noticed this...

![image](https://cloud.githubusercontent.com/assets/6358545/13775875/e3a21580-ea9e-11e5-8d58-fe5edbae969e.png)

**Comment by jsharkey13** [comment]
Haha; I like this bug, and it was easy to find the cause of it!
It's caused by this function: [shuffleChoiceQuestionsChoices(...)](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/api/managers/QuestionManager.java#L429) using the userId's hash again and again for each question on a page (in fact, I think it might even be more global than that?).
