### ISSUE TITLE
Assign book page

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#668]
From book page, click on any chapter.  Modal appears showing icon for each chapter, with two links: 'view page' and 'assign'.  Having watched many teachers use this page, they invariably click on the icon instead of clicking on the 'view page' link.  

Request to make the icon a link to that page, and remove the 'view page' text.  Leave the 'assign' text and link.

**Comment by jsharkey13** [comment]
This actually turns out to be a content thing, not an app thing.

I assume you'd like the region in the box of the below image to be a link:
![image](https://cloud.githubusercontent.com/assets/8060558/13880233/468af2f4-ed13-11e5-883e-c5843c6ea8c2.png)

In which case this is straightforward but tedious. I'd feel happier leaving the "View Page" link there though, for old browsers and accessibility.

**Comment by jsharkey13** [comment]
I made all the icons links; it did no harm and is probably a good idea. I've not removed the other links, though I fixed a few broken board parts.

It'll go live with the next content push, but should now be on staging.

**Comment by hjp22** [comment]
Yes, that's the region.
The link *could* stay.  However, I still think there's a case to remove it.  They have just come from the Book page, where they click on the chapter logo and title to access that chapter.  They don't click on linked text that says 'View chapter'.  The Rectangle does however change colour when they hover over it, making it clear it's a link.  
![bookpage](https://cloud.githubusercontent.com/assets/8695925/13883150/160ddd6e-ed20-11e5-8575-44fb4b1f4822.JPG)
