### ISSUE TITLE
Elevate to teacher fails first time

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#684]
From the admin/usermanager page, you find a user, then click the right user to select, but clicking the "Elevate to" button does nothing. From memory, I believe this is an issue that has previously been found and fixed, reappeared and fixed again. (I cannot find the issue in github though; it's an app issue rather than a content one I figure.)

Refreshing the page then pasting the user name in again, search again, click again is still a usable work-around.

I'm using Win 10 on dell i7 laptop, chrome v 49.0.2623.112 m

**Comment by jsharkey13** [comment]
This is a known bug, and I'll have a look into fixing it again - but Alistair looked into it and found it very tricky. It's not our code that the problem lies in, but some that we use from outside I think. I suggest clicking the button before doing anything, and refreshing the page. This will always ensure it works; otherwise sometimes it will work and sometimes it will not.

**Comment by jsharkey13** [comment]
This was fixed at the same time as #685 in https://github.com/ucam-cl-dtg/isaac-app/commit/bbeee77de2743c18badd12501eb0e409f53c33a2
