### ISSUE TITLE
Brackets should allow for some space to the right of their arguments to show docking points.

### ISSUE THREAD

**Issue by Morpheu5** [ucam-cl-dtg/isaac-app#690]

**Comment by ul208** [comment]
I'm not sure I understand what this issue was exactly, but was it possibly  related to this?

![untitled](https://cloud.githubusercontent.com/assets/15194006/15816193/9d5f7146-2bc9-11e6-9632-8d61f14b6d4c.png)
The currently highlighted docking point is the one yielding a Sigma *inside* the brackets but outside the square root. Probably not the result the user would predict given that the dot lies outside the brackets.

**Comment by Morpheu5** [comment]
Correct.

-- 
Andrea Franceschini -- http://andreafranceschini.org
    "A field is a domain"
Il 06 giu 2016 9:34 AM, "Umberto Lupo" <notifications@github.com> ha
scritto:

**Comment by Morpheu5** [comment]
Or not. It was for brackets only.
