### ISSUE TITLE
Hexagons and their symbols often far apart when dragging

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#708]
This is to document an issue which has been orally raised already.  Hopefully made self-explanatory by the screenshot.  I'm using Firefox 46.0.1 but the issue has been observed in Chrome too.

![eqneditorissue](https://cloud.githubusercontent.com/assets/15194006/15704638/80176c4a-27e3-11e6-9cab-644117c4204e.png)

**Comment by jsharkey13** [comment]
This was fixed in https://github.com/ucam-cl-dtg/isaac-app/commit/a3f09f24bcf1848a6d1bbd7610442b0e3dd5d7c6

**Comment by ul208** [comment]
@jsharkey13 I notice that the commit you mention was made 10 days ago, but the screenshot I took is from 5 days ago. If the issue was fixed then how can this be?

**Comment by jsharkey13** [comment]
The version on staging is (was) the same as the live version, it will never be the (unstable) up-to-date version seen on dev. But since dev goes up and down like a yo-yo, you should always use staging and just trust us when we say it's fixed!

(Though do test it once we do a release to test/staging before a release to live!)
