### ISSUE TITLE
search bar only works once

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#732]
The search bar only allows you to use it once. You can then open it and type in your query, hit search and it just disappears. 

For example:
I search for newton - hit search. 
Click on Newton III - that page comes up
Click on the search icon to search for something else, hit search, the search overlay disappears and nothing happens.

This also happens if search for something and then don't click on anything but go back to the page you were on. You then can't search for anything. 
While you are on the search page you can search however many times you want. 

The problem goes away when you hard refresh the page. This happens on both Safari and Chrome and on any page.

**Comment by donderful** [comment]
The problem is caused by line 323 in router.js:
`return $stateParams.types.split(",");`

From console log, **$stateParams.types** seems to be an array. For instance,
`["isaacConceptPage", "isaacQuestionPage"]`

You can only invoke split on strings, so the whole thing crashes.

If line 323 is replaced with code
`return $stateParams.types;`

Everything seems to work fine. But I am not sure if **$stateParams.types** could actually be a string.

**Comment by donderful** [comment]
Did some more checking - looks like **$stateParams.types** could be a string sometimes. 

If you hard refresh on the search page, console log prints out the string
`isaacConceptPage, isaacQuestionPage` instead.

By changing line 323 into this piece of code...
```
// object is actually a string, with items seperated by commas...
if (typeof $stateParams.types == "string" || (typeof $stateParams.types == "object" && $stateParams.types.constructor === String)) {
    // return the items in the string as an array of strings
    return $stateParams.types.split(",");
} else {
    // object is an array of strings already
    return $stateParams.types;
}
```
The thing should work.
