### ISSUE TITLE
Events - displays 'Availability' when not using the Isaac booking system

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#743]
View https://isaacphysics.org/events/19102016canterbury
Displays: 'Availability 40 spaces'
This should not be displayed as the event is not using the Isaac booking system: 
"eventStatus": "CLOSED"

**Comment by allydavies** [comment]
Had previously opened this issue in Content https://github.com/ucam-cl-dtg/rutherford-content/issues/437
(obviously should be here in app):

After the release over the w/e of 10+11 Sept, all student workshops, CPDs, online and live all show Availability: X spaces near the top of the page.
Example here:
![image](https://cloud.githubusercontent.com/assets/10402385/18467371/a33470e6-7997-11e6-9ed7-956f4b9a59ef.png)

All the jsons for these events have eventStatus set to CLOSED.

This is a problem because the eventbrite booking button at the bottom of the page then appears to conflict with the Availability as indicated above. Could certainly cause user frustration is it says "Availability: 40 spaces", and then at the bottom says the event is full.
![image](https://cloud.githubusercontent.com/assets/10402385/18467419/cc963dc0-7997-11e6-9f82-f5d3219e00a3.png)
