### ISSUE TITLE
Clean Up ANSWER_QUESTION Logs

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#790]
The `ANSWER_QUESTION` log event contains an awful lot of unnecessary junk:
```json
{
  "answer": {
    "id": null,
    "_id": null,
    "tags": null,
    "type": "choice",
    "level": null,
    "title": null,
    "value": "No",
    "layout": null,
    "version": null,
    "children": [
      
    ],
    "encoding": "markdown",
    "subtitle": null,
    "published": false,
    "attribution": null,
    "relatedContent": null
  },
  "correct": true,
  "questionId": "ch_d_p3|d2626a79-66ea-47b1-8e7a-3e841c12dc88",
  "explanation": {
    "id": null,
    "_id": null,
    "tags": [
      
    ],
    "type": "content",
    "level": null,
    "title": null,
    "value": null,
    "layout": null,
    "version": null,
    "children": [
      
    ],
    "encoding": "markdown",
    "subtitle": null,
    "published": false,
    "attribution": null,
    "relatedContent": null
  },
  "dateAttempted": 1486598329934
}
```

All of the `null` tags could easily be dropped, as could the `published: false,` lines and the empty `children` tags. This is a space saving of about 60% on this event, and makes the log much easier to read too!

The log is created in [`QuestionFacade.java`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/api/QuestionFacade.java#L211), and it may be that the [`PgLogManager.java`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/dao/PgLogManager.java#L478) ObjectMapper is the place to fix it.

**Comment by jsharkey13** [comment]
This will also affect the [`QUESTION_ATTEMPT_RATE_LIMITED`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/api/QuestionFacade.java#L189-L198) events too.

**Comment by mlt47** [comment]
The simple solution:
Jackson implements a @JsonInclude annotation which can be given the argument NON_EMPTY, NON_NULL or NON_DEFAULT to filter on the values of the fields when serialising. This annotation can be set on either the class or on individual field level of the DTOs so it is quite flexible.

The problem with the simple solution:
This would mean that the JSON that is sent to the front-end would also not include those empty/null fields...
It doesn't seem to affect the web app from what I've seen but I can't be certain that something somewhere won't break. 

If this is good enough then let me know, I doubt it is. 
Otherwise, we could go down the route of creating our own annotation (@DoNotLogIf("defaultValueForField")) with a custom serialiser, or there might be a slightly quicker solution using setMixinAnnotations or something, and having a separate object mapper for logging.

**Comment by sacummins** [comment]
I think you can configure the jackson serialiser used in the logging code to ignore null values. This might be better than marking each POJO field. I will have a look at where it is when I have some time and let you know.

**Comment by mlt47** [comment]
Ah cool, something like that would be good, I will let you know if I get around to looking at it before you. Thanks!

**Comment by jsharkey13** [comment]
@mlt47 Do we think this is fixed now?

**Comment by mlt47** [comment]
Yes, it now does not store null valued fields in the JSON blob.
It does still store "empty" values ("", [], etc.) but I think that we should stick to that so that, when looking back over a  log event which was causing a problem, there is no ambiguity whether the missing value was an empty-value or a null-value.
